version: '3.8'

services:
  fastapi_app:
    build:
      context: . 
    container_name: fastapi_app_container
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env

volumes:
  mongo_data:
